spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        mensaje-in:
          destination: mensaje
          contentType: application/json
        mensaje-out:
          destination: mensaje
          contentType: application/json

